// (c) 2025 Beem Media. All rights reserved.

#pragma once

#include "ImageLib/ImgLib.h"
#include <Windows.h>

class SgImgLibEdit : public SgImgLib
{
public:
	SgImgLibEdit();
	SgImgLibEdit(sg_uint32 nMaxEntries);
	~SgImgLibEdit();

	bool AddBitmap(LPSTR szFilename);
	bool AddEntry(sg_uint16 x, sg_uint16 y, sg_uint16 nWidthSrc, sg_uint16 nHeightSrc, sg_uint16 nWidth, sg_uint16 nHeight, sg_uint16 nBitmap, sg_uint16 nFrames, LPSTR szImageName);
	bool SetEntry(sg_uint32 nReference, sg_uint16 x, sg_uint16 y, sg_uint16 nWidthSrc, sg_uint16 nHeightSrc, sg_uint16 nWidth, sg_uint16 nHeight, sg_uint16 nBitmap, sg_uint16 nFrames, LPSTR szImageName);
	bool AutoGenerateData(sg_uint16 nBitmap, sg_uint16 nWidth, sg_uint16 nHeight, sg_uint16 nXSpacing, sg_uint16 nYSpacing, BOOL bClear);
	void ClearDataBase();
	bool SaveData(LPSTR szFilename);
	bool LoadData(LPSTR szFilename);
	bool BuildLibrary(LPSTR szFilename);
	bool ImportLibrary(LPSTR szFilename);

	void CopyImageToDC(HDC hdcDest, sg_uint32 nEntry, int x, int y, BOOL bTransp);
	void StretchImageToDC(HDC hdcDest, sg_uint32 nEntry, int x, int y, int nWidth, int nHeight, BOOL bTransp);

private:
	HBITMAP m_hBitmap[MAX_BITMAPS] = { };

private:
	void CloseMainBitmaps();
	void OpenMainBitmaps();
};
